In [1]:
# # Introdução ao Pandas
# # https://www.youtube.com/watch?v=an54pc9BW4I&list=PLyqOvdQmGdTR46HUxDA6Ymv4DGsIjvTQ-&index=12
# Documentação:
# https://pandas.pydata.org/pandas-docs/stable/

In [ ]:
# Pandas é utilizado para trabalhar com data frame(tabelas, com linhas e colunas)

In [19]:
import pandas as pd
# criando nosso proprio data frame.
alunos = {'Nome':['Rafael', 'Robert', 'Roger', 'Pedro'], # dicionário alunos
         'Nota':[8, 7, 3, 1],
         'Aprovado':['Sim', 'Sim', 'Não', 'Não']}

In [7]:
# transformando dicionário em data frame
dataFrame = pd.DataFrame(alunos)

In [8]:
print(dataFrame)

     Nome  Nota Aprovado
0  Rafael     8      Sim
1  Robert     7      Sim
2   Roger     3      Não
3   Pedro     1      Não


In [9]:
objeto1 = pd.Series([2, 4, 6, 8]) # Series() - cria um tipo de vetor unid. com índices. Diferente do array
print(objeto1)

0    2
1    4
2    6
3    8
dtype: int64


In [23]:
import numpy as np
array1 = np.array([2, 4, 6, 8])
array2 = np.array([(2, 4, 6, 8), (1, 2, 3, 4)])
print(array1)
print('\n')
print(array2)

[2 4 6 8]


[[2 4 6 8]
 [1 2 3 4]]


In [24]:
objeto2 = pd.Series(array1) # convertendo array(unidimensional) em series.
print(objeto2)

0    2
1    4
2    6
3    8
dtype: int32
